name: 'Release Change Logs'
description: 'Genereate commit logs from last released/tag to HEAD'
branding:
  icon: activity
  color: gray-dark
inputs:
  feature:  # id of input
    description: 'prefix message for feature commits'
    required: false
    default: 'FEATURE'
  bugs:  # id of input
    description: 'prefix message for bugfix commits'
    required: false
    default: 'BUGFIX'
  custom_tags:
    description: 'Custom tags as JSON String'
    required: false
    default: '{}'
  commit_hash:
    description: 'Commit Hash'
    required: false
    default: ''
outputs:
  latest_tag: # id of output
    description: 'Latest Tag'
  logs-on-json: # id of output
    description: 'commit logs on json format'
  change-logs: # id of output
    description: 'change logs based on commit messages used for release messages'
runs:
  using: 'node20'
  main: 'dist/index.js'
